package appointment;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.ChoiceBox;

public class AppointmentCreatorController {
	@FXML
	private TextField AppointmentTitle;
	@FXML
	private HBox AppointmentStartDate;
	@FXML
	private TextField AppointmentStartTime;
	@FXML
	private DatePicker AppointmentEndDate;
	@FXML
	private TextField AppointmentEndTime;
	@FXML
	private CheckBox AppointmentRegularlyOnOff;
	@FXML
	private ChoiceBox AppointmentRegularlyType;
	@FXML
	private CheckBox AppointmentAllDay;
	@FXML
	private Button AppoinmentPinNote;
	@FXML
	private CheckBox AppointmentAlarmOnOff;
	@FXML
	private DatePicker AppointmentAlarmDate;
	@FXML
	private TextField AppointmentAlarmTime;
	@FXML
	private Button AppointmentSave;

	// Event Listener on Button[#AppoinmentPinNote].onAction jk
	@FXML
	public void appointmentPinNotePress(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AppointmentSave].onAction
	@FXML
	public void appointmentSavePress(ActionEvent event) {
		// TODO Autogenerated
	}
}
