package task;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.Slider;

import javafx.scene.input.MouseDragEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.ChoiceBox;

public class CreateTaskController {
	@FXML
	private TextField title;
	@FXML
	private DatePicker pickStart;
	@FXML
	private DatePicker pickEnd;
	@FXML
	private TextField hoursField;
	@FXML
	private TextField minutesField;
	@FXML
	private Slider durationSlider;
	@FXML
	private CheckBox regularOnOff;
	@FXML
	private ChoiceBox choiceRegular;
	@FXML
	private CheckBox autoSortOnOff;
	@FXML
	private Button saveButton;

	// Event Listener on TextField[#hoursField].onAction
	@FXML
	public void hoursField(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#minutesField].onAction
	@FXML
	public void minutesField(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Slider[#durationSlider].onMouseDragReleased
	@FXML
	public void slideDuration(MouseDragEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#regularOnOff].onAction
	@FXML
	public void regularSwitch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#autoSortOnOff].onAction
	@FXML
	public void autosortSwitch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveTask(ActionEvent event) {
		// TODO Autogenerated
	}
}
