package task;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import java.net.URL;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.ResourceBundle;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.control.Slider;
import javafx.scene.control.Spinner;
import javafx.scene.input.MouseDragEvent;
import javafx.scene.control.CheckBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.ChoiceBox;

public class CreateTaskController implements Initializable {
	@FXML
	private TextField title;
	@FXML
	private DatePicker pickStart;
	@FXML
	private DatePicker pickEnd;
	@FXML
	private TextField hoursField;
	@FXML
	private TextField minutesField;
	@FXML
	private Spinner<Long> startHour;
	@FXML
	private Spinner<Long> endHour;
	@FXML
	private Spinner<Long> startMinute;
	@FXML
	private Spinner<Long> endMinute;
	@FXML
	private Slider durationSlider;
	@FXML
	private Slider durationSlider1;
	@FXML
	private CheckBox regularOnOff;
	@FXML
	private ChoiceBox<String> choiceRegular;
	@FXML
	private CheckBox autoSortOnOff;
	@FXML
	private Button saveButton;
	
	ObservableList<String> regularlyType= FXCollections.observableArrayList("täglich", "wöchentlich", "monatlich");

	
	public static final long INIT_VALUE_HOURS = 1;
	public static final long INIT_VALUE_MINUTES = 1;
	LocalDate startDate;
	LocalDate endDate;

	// Event Listener on TextField[#hoursField].onAction
	@FXML
	public void hoursField(ActionEvent event) {

		
	}
	// Event Listener on TextField[#minutesField].onAction
	@FXML
	public void minutesField(ActionEvent event) {

	}
	// Event Listener on Slider[#durationSlider].onMouseDragReleased
	@FXML
	public void slideDuration(MouseDragEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#regularOnOff].onAction
	@FXML
	public void regularSwitch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#autoSortOnOff].onAction
	@FXML
	public void autosortSwitch(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#saveButton].onAction
	@FXML
	public void saveTask(ActionEvent event) {
		// TODO Autogenerated
	}

	private static final long endTimeHour=0;
	private static final long endTimeMinute=0;


	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {

		
		choiceRegular.setVisible(false);
		regularOnOff.setSelected(false);
			
		if(regularOnOff.isSelected()==true)	
		{
			choiceRegular.setVisible(true);
		}	
			
		
		
		choiceRegular.setItems(regularlyType);
		
		durationSlider.setValue(Math.round(INIT_VALUE_HOURS));
		durationSlider1.setValue(Math.round(INIT_VALUE_MINUTES));
		

		hoursField.setText(new Long(Math.round(INIT_VALUE_HOURS)).toString());
		minutesField.setText(new Long(Math.round(INIT_VALUE_MINUTES)).toString());
		if(endHour.getValueFactory().getValue() == startHour.getValueFactory().getValue() || endMinute.getValueFactory().getValue() == startMinute.getValueFactory().getValue()) 
		{
		endHour.getValueFactory().setValue(new Long(endTimeHour+INIT_VALUE_HOURS));
		endMinute.getValueFactory().setValue(new Long(endTimeMinute+INIT_VALUE_MINUTES));
		}
				
		regularOnOff.selectedProperty().bindBidirectional(choiceRegular.visibleProperty());
		hoursField.textProperty().bindBidirectional(durationSlider.valueProperty(), NumberFormat.getNumberInstance());
		minutesField.textProperty().bindBidirectional(durationSlider1.valueProperty(), NumberFormat.getNumberInstance());
		endHour.getValueFactory().valueProperty().bindBidirectional(startHour.getValueFactory().valueProperty());
		
		
	}
}
