package note;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.layout.GridPane;
import task.CreateTaskController;
import javafx.scene.control.*;

public class NotesViewController implements Initializable
{
	@FXML
	private GridPane NoteContent;
	@FXML
	private Button backButton;
	@FXML
	notesLabel Label = new notesLabel();
	@FXML
	private Button forwardButton;
	@FXML
	static ArrayList<Label> notesabels = new ArrayList<>();
	static ArrayList<String> notes = new ArrayList<String>();
	
	// Event Listener on Button[#backButton].onAction
	@FXML
	public void backButtonPress(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button[#forwardButton].onAction
	@FXML
	public void forwardButtonPress(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	@FXML
	public void creatNotesView()
	{
		for (int i = 0; i < notes.size(); i++)
		{
			Label notelabel = new Label();
			notelabel.setText(notes.get(i));
			NoteContent.add(notelabel, 0, i);
		}	
	}
	@Override
	public void initialize(URL location, ResourceBundle resources)
	{
		// TODO Auto-generated method stub
		notes.add("Note: Das ist eine Test Notiz");
		notes.add("Note: Das ist eine zweite Test Notiz");
		notes.add("Note: Das ist eine Test Notiz");
		notes.add("Note: Das ist eine zweite Test Notiz");
		notes.add("Note: Das ist eine Test Notiz");
		notes.add("Note: Das ist eine zweite Test Notiz");
		creatNotesView();
	}
}
